1./*Crea un procedimiento que sube el precio de venta un 5% al artículo que más vende. UNIDADES VENDIDAS*/

CREATE OR REPLACE PROCEDURE AUMENTOPRECIO
AS 
BEGIN
UPDATE ARTICULOS SET PRECIO_VENTA=(PRECIO_VENTA*0.5)+PRECIO_VENTA WHERE (ARTICULO,COD_FABRICANTE,PESO,CATEGORIA)IN(SELECT A.ARTICULO,A.COD_FABRICANTE,A.PESO,A.CATEGORIA FROM VENTAS V,ARTICULOS A  WHERE 
A.ARTICULO=V.ARTICULO AND A.COD_FABRICANTE=V.COD_FABRICANTE AND A.PESO=V.PESO AND A.CATEGORIA=V.CATEGORIA 
GROUP BY A.ARTICULO,A.COD_FABRICANTE,A.PESO,A.CATEGORIA,PRECIO_VENTA HAVING SUM(UNIDADES_VENDIDAS) IN
(SELECT MAX(SUM(UNIDADES_VENDIDAS)) FROM VENTAS GROUP BY ARTICULO,COD_FABRICANTE,PESO,CATEGORIA));
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR');
END AUMENTOPRECIO;
EXECUTE AUMENTOPRECIO;


SELECT A.ARTICULO,A.COD_FABRICANTE,A.PESO,A.CATEGORIA,PRECIO_VENTA FROM VENTAS V,ARTICULOS A  WHERE 
A.ARTICULO=V.ARTICULO AND A.COD_FABRICANTE=V.COD_FABRICANTE AND A.PESO=V.PESO AND A.CATEGORIA=V.CATEGORIA 
GROUP BY A.ARTICULO,A.COD_FABRICANTE,A.PESO,A.CATEGORIA,PRECIO_VENTA HAVING SUM(UNIDADES_VENDIDAS)=
(SELECT MAX(SUM(UNIDADES_VENDIDAS)) FROM VENTAS GROUP BY ARTICULO,COD_FABRICANTE,PESO,CATEGORIA);

2./*Crea una función que nos devuelve el salario máximo de un departamento que pasamos como parámetro.*/


CREATE OR REPLACE  FUNCTION  EJER2(NDEPT NUMBER)
RETURN NUMBER
AS
V_SALARIO NUMBER(5);
BEGIN 
SELECT SALARIO INTO V_SALARIO FROM EMPLE WHERE DEPT_NO = NDEPT GROUP BY DEPT_NO,SALARIO HAVING SALARIO IN (SELECT MAX(SALARIO)FROM EMPLE WHERE DEPT_NO = NDEPT GROUP BY DEPT_NO);
RETURN V_SALARIO;
END EJER2;

BEGIN
DBMS_OUTPUT.PUT_LINE(EJER2(20));
END;



3./*Crea un procedimiento que le pasamos el número de departamento y haciendo uso de la función anterior,
 nos muestra por pantalla el empleado que más gana en ese departamento.*/

 CREATE OR REPLACE PROCEDURE EJER3(NDEPT NUMBER)
 AS
 VP_SALARIO NUMBER(5);
 V_APELLIDO VARCHAR2(20);
 BEGIN
 VP_SALARIO:=EJER2(NDEPT);
 SELECT APELLIDO INTO V_APELLIDO FROM EMPLE WHERE DEPT_NO = NDEPT AND SALARIO = VP_SALARIO;
 DBMS_OUTPUT.PUT_LINE('El salario maximo del departamento'||' '||NDEPT||' ES '||VP_SALARIO||' PERTENECE A  '||V_APELLIDO);
 EXCEPTION
 WHEN OTHERS THEN
 DBMS_OUTPUT.PUT_LINE('ERROR');  
 END EJER3;


 EXECUTE EJER3(10);
 

/*CON ESTE PROCEDIMIENTO  PODEMOS TENER PROBLEMAS SI TENEMOS VARIAS PERSONAS QUE COBREN LO MISMO POR LO CUAL LO HAREMOS CON UN CURSOR*/
CREATE OR REPLACE PROCEDURE EJER3_1(NDEPT NUMBER)
 AS
 VP_SALARIO NUMBER(5);
 CURSOR C_EMPLE IS SELECT APELLIDO FROM EMPLE WHERE DEPT_NO = NDEPT AND SALARIO = VP_SALARIO;
 BEGIN
 VP_SALARIO:=EJER2(NDEPT);
FOR V_REG IN C_EMPLE LOOP
  DBMS_OUTPUT.PUT_LINE('El salario maximo del departamento'||' '||NDEPT||' ES '||VP_SALARIO||' PERTENECE A  '||V_REG.APELLIDO);
END LOOP;
END EJER3_1;
 EXECUTE EJER3_1(20);

4./*Crea un procedimiento que nos muestra los artículos de un cierto fabricante y una categoría.*/
CREATE OR REPLACE PROCEDURE EJER4(NFAB VARCHAR2,CAT VARCHAR2)
AS
CURSOR  INFO  IS SELECT ARTICULO,A.COD_FABRICANTE,PESO,CATEGORIA FROM ARTICULOS A,FABRICANTES F WHERE A.COD_FABRICANTE = F.COD_FABRICANTE AND NOMBRE=NFAB AND CATEGORIA=CAT;
BEGIN
FOR V_REG IN INFO LOOP
    DBMS_OUTPUT.PUT_LINE(RPAD(V_REG.ARTICULO,15)||RPAD(V_REG.COD_FABRICANTE,15)||RPAD(V_REG.PESO,15)||RPAD(V_REG.CATEGORIA,15));
END LOOP;
END EJER4;
EXECUTE EJER4('CALVO','Primera');


5./*Crea un procedimiento en el que vemos por cada departamento (muestra el departamento) sus respectivos empleados. Utiliza cursores anidados.*/

CREATE OR REPLACE PROCEDURE VER_DEPT_EMPLEADOS
AS 
CURSOR C1 IS SELECT * FROM DEPART;
CURSOR C2(DEPT NUMBER) IS SELECT APELLIDO,OFICIO,SALARIO FROM EMPLE WHERE DEPT_NO=DEPT;
BEGIN
FOR V_REG IN C1 LOOP
 DBMS_OUTPUT.PUT_LINE(RPAD(V_REG.DEPT_NO,15)||RPAD(V_REG.DNOMBRE,15)||RPAD(V_REG.LOC,15));
 DBMS_OUTPUT.PUT_LINE(' ');
 FOR V_REG2 IN C2(V_REG.DEPT_NO) LOOP
   DBMS_OUTPUT.PUT_LINE(RPAD(V_REG2.APELLIDO,20)||RPAD(V_REG2.OFICIO,20)||RPAD(V_REG2.SALARIO,20));
 END LOOP;
END LOOP;
END VER_DEPT_EMPLEADOS;
EXECUTE VER_DEPT_EMPLEADOS;


